// Auto-generated by scripts/amazon-asin/apply_asins.py
// Do not edit by hand. Re-run apply_asins.py after updating the CSV.
// Source: nutri_asins.csv (manual SiteStripe curation)

export const AMAZON_ASINS: Record<string, string> = {
};
